In [13]:
import os, shutil, re
from helpers import *
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal
from scipy.io import wavfile
import librosa
import librosa.display
import datetime

%matplotlib inline

In [24]:
def preprocess(samples, sample_rate, multiplier=1):
    sr = sample_rate * multiplier
    padded = np.zeros(sr)
    samples = samples[:sr]
    padded[:samples.shape[0]] = samples
    print(padded)
    return padded

In [27]:
wavpath = os.getcwd() + "/audio/taylor_12_06_01/no_voice/12_06/lights-on/ch1/00000.wav"
sample_rate, samples = wavfile.read(wavpath)
dataPts = len(samples)
window = round(dataPts * .8)
difference = dataPts - window
chunk = int(difference / 10) 

for i in range(10):
    x = i * chunk
    changed = samples[x:window+x]
    print(x, window+x)
    print(samples)
    changed = preprocess(changed, sample_rate, 1)
    S = librosa.feature.melspectrogram(changed, sr=sample_rate, n_mels=128, fmax=512)
    log_S = librosa.power_to_db(S, ref=np.max)
    fig = plt.figure(figsize=(1.28, 1.28), dpi=100, frameon=False)
    ax = plt.Axes(fig, [0., 0., 1., 1.])
    ax.set_axis_off()
    fig.add_axes(ax)
    plt.axis('off')
    librosa.display.specshow(log_S)                          
    plt.savefig(os.getcwd() + "/test/test_{}".format(i))
    plt.close()

0 6554
[-4841 -4831 -4822 ... -4514 -4489 -4466]
[-4841. -4831. -4822. ...     0.     0.     0.]
163 6717
[-4841 -4831 -4822 ... -4514 -4489 -4466]
[-5363. -5321. -5278. ...     0.     0.     0.]
326 6880
[-4841 -4831 -4822 ... -4514 -4489 -4466]
[-3146. -3134. -3124. ...     0.     0.     0.]
489 7043
[-4841 -4831 -4822 ... -4514 -4489 -4466]
[-6652. -6595. -6528. ...     0.     0.     0.]
652 7206
[-4841 -4831 -4822 ... -4514 -4489 -4466]
[-1659. -1596. -1531. ...     0.     0.     0.]
815 7369
[-4841 -4831 -4822 ... -4514 -4489 -4466]
[-4692. -4638. -4565. ...     0.     0.     0.]
978 7532
[-4841 -4831 -4822 ... -4514 -4489 -4466]
[1267. 1334. 1409. ...    0.    0.    0.]
1141 7695
[-4841 -4831 -4822 ... -4514 -4489 -4466]
[6058. 6254. 6439. ...    0.    0.    0.]
1304 7858
[-4841 -4831 -4822 ... -4514 -4489 -4466]
[5163. 5190. 5221. ...    0.    0.    0.]
1467 8021
[-4841 -4831 -4822 ... -4514 -4489 -4466]
[4216. 4167. 4115. ...    0.    0.    0.]
